import { Category, Coupon, Product, Review } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "cat-coffee",
    slug: "coffee",
    name: "Coffee",
    nameAr: "قهوة",
    description: "Single-origin beans and signature roasts, sourced from celebrated estates.",
    image: "/images/categories/coffee.svg",
    productCount: 6,
  },
  {
    id: "cat-chocolate",
    slug: "chocolate",
    name: "Chocolate",
    nameAr: "شوكولاتة",
    description: "Hand-crafted couverture chocolate with rare cacao origins.",
    image: "/images/categories/chocolate.svg",
    productCount: 6,
  },
  {
    id: "cat-nuts",
    slug: "nuts",
    name: "Nuts",
    nameAr: "مكسرات",
    description: "Slow-roasted premium nuts, seasoned with restraint and precision.",
    image: "/images/categories/nuts.svg",
    productCount: 4,
  },
  {
    id: "cat-accessories",
    slug: "accessories",
    name: "Accessories",
    nameAr: "أدوات القهوة",
    description: "Brewing instruments for the discerning home barista.",
    image: "/images/categories/accessories.svg",
    productCount: 4,
  },
  {
    id: "cat-gift-boxes",
    slug: "gift-boxes",
    name: "Gift Boxes",
    nameAr: "صناديق الهدايا",
    description: "Curated gift collections, wrapped in the LEOR signature style.",
    image: "/images/categories/gift-boxes.svg",
    productCount: 2,
  },
  {
    id: "cat-seasonal",
    slug: "seasonal",
    name: "Seasonal",
    nameAr: "منتجات موسمية",
    description: "Limited editions that mark the season — here, then gone.",
    image: "/images/categories/seasonal.svg",
    productCount: 2,
  },
];

const img = (slug: string, n = 3) =>
  Array.from({ length: n }, (_, i) => `/images/products/${slug}-${i + 1}.svg`);

export const PRODUCTS: Product[] = [
  {
    id: "p-001",
    slug: "ethiopian-yirgacheffe",
    name: "Ethiopian Yirgacheffe",
    nameAr: "قهوة إثيوبية يرغاتشيف",
    category: "coffee",
    shortDescription: "Floral single-origin with notes of jasmine, bergamot and stone fruit.",
    description:
      "Grown at 2,100 metres in the Gedeo Zone, our Yirgacheffe lot is washed, sun-dried on raised beds and roasted lightly to preserve its delicate florality. Expect a silky body, sparkling acidity and a finish of apricot and honey.",
    price: 95,
    currency: "SAR",
    images: img("ethiopian-yirgacheffe"),
    weight: "250g",
    origin: "Ethiopia",
    sku: "LEOR-CF-001",
    barcode: "6281000000018",
    stock: 42,
    lowStockThreshold: 10,
    rating: 4.9,
    reviewCount: 128,
    tags: ["single-origin", "light-roast", "washed"],
    attributes: { Roast: "Light", Process: "Washed", Altitude: "2,100m", Notes: "Jasmine, bergamot, apricot" },
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    onSale: false,
    createdAt: "2026-01-12T09:00:00Z",
  },
  {
    id: "p-002",
    slug: "colombian-geisha",
    name: "Colombian Geisha Reserve",
    nameAr: "قهوة كولومبية جيشا",
    category: "coffee",
    shortDescription: "A rare micro-lot Geisha with layered florals and a champagne-like finish.",
    description:
      "From a single farm in Huila, this Geisha micro-lot is among the most decorated coffees we have ever sourced. Roasted to order in small batches. Limited allocation per season.",
    price: 240,
    salePrice: 210,
    currency: "SAR",
    images: img("colombian-geisha"),
    weight: "200g",
    origin: "Colombia",
    sku: "LEOR-CF-002",
    barcode: "6281000000025",
    stock: 14,
    lowStockThreshold: 8,
    rating: 5.0,
    reviewCount: 64,
    tags: ["geisha", "micro-lot", "limited"],
    attributes: { Roast: "Light", Process: "Honey", Altitude: "1,900m", Notes: "Orange blossom, peach, silk" },
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    onSale: true,
    createdAt: "2026-02-02T09:00:00Z",
  },
  {
    id: "p-003",
    slug: "leor-signature-espresso",
    name: "LEOR Signature Espresso",
    nameAr: "إسبريسو ليور المميز",
    category: "coffee",
    shortDescription: "Our house blend — dark chocolate, caramel and a velvet crema.",
    description:
      "A meticulously balanced blend of Brazilian and Ethiopian lots, developed over two years for the perfect espresso: heavy body, cocoa sweetness and a crema that holds. Equally at home in milk drinks.",
    price: 78,
    currency: "SAR",
    images: img("leor-signature-espresso"),
    weight: "500g",
    origin: "Blend — Brazil & Ethiopia",
    sku: "LEOR-CF-003",
    barcode: "6281000000032",
    stock: 88,
    lowStockThreshold: 15,
    rating: 4.8,
    reviewCount: 214,
    tags: ["espresso", "blend", "house"],
    attributes: { Roast: "Medium-dark", Process: "Natural & washed", Notes: "Dark chocolate, caramel, hazelnut" },
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    onSale: false,
    createdAt: "2025-11-20T09:00:00Z",
  },
  {
    id: "p-004",
    slug: "yemeni-mocha-haraz",
    name: "Yemeni Mocha Haraz",
    nameAr: "قهوة يمنية موكا حراز",
    category: "coffee",
    shortDescription: "Ancient heirloom varietals — wild berries, spice and dried fig.",
    description:
      "Cultivated on the terraced cliffs of the Haraz mountains as it has been for five centuries. Naturally processed, intensely aromatic, unmistakably Yemeni.",
    price: 165,
    currency: "SAR",
    images: img("yemeni-mocha-haraz"),
    weight: "250g",
    origin: "Yemen",
    sku: "LEOR-CF-004",
    barcode: "6281000000049",
    stock: 26,
    lowStockThreshold: 10,
    rating: 4.9,
    reviewCount: 89,
    tags: ["heirloom", "natural", "arabica"],
    attributes: { Roast: "Medium", Process: "Natural", Altitude: "2,200m", Notes: "Wild berry, cardamom, fig" },
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    onSale: false,
    createdAt: "2026-05-15T09:00:00Z",
  },
  {
    id: "p-005",
    slug: "decaf-swiss-water",
    name: "Swiss Water Decaf",
    nameAr: "قهوة منزوعة الكافيين",
    category: "coffee",
    shortDescription: "Chemical-free decaffeination that keeps every note intact.",
    description:
      "A Colombian lot decaffeinated with the Swiss Water process — 99.9% caffeine-free with none of the flavour compromise. Chocolate, red apple and brown sugar.",
    price: 68,
    currency: "SAR",
    images: img("decaf-swiss-water"),
    weight: "250g",
    origin: "Colombia",
    sku: "LEOR-CF-005",
    barcode: "6281000000056",
    stock: 31,
    lowStockThreshold: 10,
    rating: 4.6,
    reviewCount: 47,
    tags: ["decaf", "swiss-water"],
    attributes: { Roast: "Medium", Process: "Swiss Water", Notes: "Chocolate, red apple, brown sugar" },
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    onSale: false,
    createdAt: "2025-12-05T09:00:00Z",
  },
  {
    id: "p-006",
    slug: "cold-brew-blend",
    name: "Cold Brew Reserve Blend",
    nameAr: "خلطة القهوة الباردة",
    category: "coffee",
    shortDescription: "Coarse-ground blend crafted for slow, sweet cold extraction.",
    description:
      "Twelve hours of patience rewarded: a blend selected for cold extraction, yielding a naturally sweet, low-acid concentrate with notes of cocoa nib and vanilla.",
    price: 72,
    salePrice: 59,
    currency: "SAR",
    images: img("cold-brew-blend"),
    weight: "400g",
    origin: "Blend — Brazil & Colombia",
    sku: "LEOR-CF-006",
    barcode: "6281000000063",
    stock: 7,
    lowStockThreshold: 10,
    rating: 4.7,
    reviewCount: 58,
    tags: ["cold-brew", "blend", "summer"],
    attributes: { Roast: "Medium", Grind: "Coarse", Notes: "Cocoa nib, vanilla, date" },
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    onSale: true,
    createdAt: "2026-04-01T09:00:00Z",
  },

  // ——— Chocolate ———
  {
    id: "p-101",
    slug: "single-origin-madagascar-70",
    name: "Madagascar 70% Single Origin",
    nameAr: "شوكولاتة مدغشقر ٧٠٪",
    category: "chocolate",
    shortDescription: "Bright red-fruit acidity from the famed Sambirano valley.",
    description:
      "Crafted from Trinitario cacao grown in the Sambirano valley, this 70% bar is stone-ground over three days for a texture of pure silk. Raspberry, citrus and a long cocoa finish.",
    price: 55,
    currency: "SAR",
    images: img("single-origin-madagascar-70"),
    weight: "80g",
    origin: "Madagascar",
    sku: "LEOR-CH-101",
    barcode: "6281000001015",
    stock: 64,
    lowStockThreshold: 15,
    rating: 4.9,
    reviewCount: 152,
    tags: ["dark", "single-origin", "bean-to-bar"],
    attributes: { Cacao: "70%", Origin: "Sambirano Valley", Texture: "Stone-ground", Notes: "Raspberry, citrus" },
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    onSale: false,
    createdAt: "2025-10-10T09:00:00Z",
  },
  {
    id: "p-102",
    slug: "pistachio-praline-collection",
    name: "Pistachio Praliné Collection",
    nameAr: "تشكيلة برالين الفستق",
    category: "chocolate",
    shortDescription: "Twelve hand-piped pralinés with roasted Iranian pistachio.",
    description:
      "Our signature praliné: slow-roasted pistachios ground to a butter, folded into white and dark couverture, and finished with a whisper of sea salt. Twelve pieces, hand-packed.",
    price: 120,
    currency: "SAR",
    images: img("pistachio-praline-collection"),
    weight: "180g",
    sku: "LEOR-CH-102",
    barcode: "6281000001022",
    stock: 38,
    lowStockThreshold: 12,
    rating: 5.0,
    reviewCount: 96,
    tags: ["praline", "pistachio", "gift"],
    attributes: { Pieces: "12", Filling: "Pistachio praliné", Shell: "Dark & white couverture" },
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    onSale: false,
    createdAt: "2025-12-01T09:00:00Z",
  },
  {
    id: "p-103",
    slug: "dark-sea-salt-85",
    name: "85% Dark with Sea Salt",
    nameAr: "شوكولاتة داكنة ٨٥٪ بملح البحر",
    category: "chocolate",
    shortDescription: "Intense Ecuadorian cacao balanced by hand-harvested fleur de sel.",
    description:
      "For purists: 85% Arriba Nacional cacao from Ecuador, its intensity lifted by crystals of fleur de sel. Minimal sugar, maximum character.",
    price: 48,
    currency: "SAR",
    images: img("dark-sea-salt-85"),
    weight: "80g",
    origin: "Ecuador",
    sku: "LEOR-CH-103",
    barcode: "6281000001039",
    stock: 52,
    lowStockThreshold: 15,
    rating: 4.7,
    reviewCount: 71,
    tags: ["dark", "sea-salt", "low-sugar"],
    attributes: { Cacao: "85%", Origin: "Ecuador", Notes: "Espresso, tobacco leaf, salt" },
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    onSale: false,
    createdAt: "2026-01-08T09:00:00Z",
  },
  {
    id: "p-104",
    slug: "date-and-tahini-bar",
    name: "Date & Tahini Milk Bar",
    nameAr: "شوكولاتة التمر والطحينة",
    category: "chocolate",
    shortDescription: "A Levantine love letter — Medjool caramel and sesame in milk chocolate.",
    description:
      "Medjool dates cooked into a soft caramel, layered with stone-ground tahini and enrobed in 45% milk couverture. Our most-requested regional creation.",
    price: 62,
    salePrice: 52,
    currency: "SAR",
    images: img("date-and-tahini-bar"),
    weight: "100g",
    sku: "LEOR-CH-104",
    barcode: "6281000001046",
    stock: 45,
    lowStockThreshold: 12,
    rating: 4.8,
    reviewCount: 84,
    tags: ["milk", "dates", "tahini", "regional"],
    attributes: { Cacao: "45% milk", Filling: "Date caramel & tahini" },
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    onSale: true,
    createdAt: "2026-05-20T09:00:00Z",
  },
  {
    id: "p-105",
    slug: "hot-chocolate-flakes",
    name: "Drinking Chocolate Flakes",
    nameAr: "رقائق الشوكولاتة الساخنة",
    category: "chocolate",
    shortDescription: "Shaved 65% couverture for the thickest, silkiest hot chocolate.",
    description:
      "Real couverture shaved into fine flakes — whisk into hot milk for a European-style drinking chocolate. No powders, no shortcuts.",
    price: 58,
    currency: "SAR",
    images: img("hot-chocolate-flakes"),
    weight: "250g",
    sku: "LEOR-CH-105",
    barcode: "6281000001053",
    stock: 29,
    lowStockThreshold: 10,
    rating: 4.8,
    reviewCount: 63,
    tags: ["drinking-chocolate", "winter"],
    attributes: { Cacao: "65%", Serving: "30g per cup" },
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    onSale: false,
    createdAt: "2025-11-02T09:00:00Z",
  },
  {
    id: "p-106",
    slug: "ruby-raspberry-bonbons",
    name: "Ruby & Raspberry Bonbons",
    nameAr: "بونبون الروبي والتوت",
    category: "chocolate",
    shortDescription: "Nine jewel-like bonbons of ruby chocolate and raspberry ganache.",
    description:
      "Naturally pink ruby couverture filled with a bright raspberry ganache. Nine pieces, each hand-polished to a mirror shine.",
    price: 98,
    currency: "SAR",
    images: img("ruby-raspberry-bonbons"),
    weight: "135g",
    sku: "LEOR-CH-106",
    barcode: "6281000001060",
    stock: 0,
    lowStockThreshold: 8,
    rating: 4.9,
    reviewCount: 42,
    tags: ["ruby", "bonbon", "gift"],
    attributes: { Pieces: "9", Shell: "Ruby couverture", Filling: "Raspberry ganache" },
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    onSale: false,
    createdAt: "2026-06-01T09:00:00Z",
  },

  // ——— Nuts ———
  {
    id: "p-201",
    slug: "royal-mixed-nuts",
    name: "Royal Mixed Nuts",
    nameAr: "مكسرات ملكية مشكلة",
    category: "nuts",
    shortDescription: "Macadamia, pecan, cashew and almond — dry-roasted, lightly salted.",
    description:
      "Our flagship mix: jumbo macadamias, Georgia pecans, whole cashews and Marcona-style almonds, dry-roasted in small batches and finished with flake salt.",
    price: 85,
    currency: "SAR",
    images: img("royal-mixed-nuts"),
    weight: "400g",
    sku: "LEOR-NT-201",
    barcode: "6281000002012",
    stock: 73,
    lowStockThreshold: 15,
    rating: 4.8,
    reviewCount: 167,
    tags: ["mixed", "roasted", "salted"],
    attributes: { Roast: "Dry, small-batch", Salt: "Flake sea salt" },
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    onSale: false,
    createdAt: "2025-09-15T09:00:00Z",
  },
  {
    id: "p-202",
    slug: "honey-glazed-almonds",
    name: "Honey-Glazed Sidr Almonds",
    nameAr: "لوز بعسل السدر",
    category: "nuts",
    shortDescription: "California almonds lacquered in rare Yemeni Sidr honey.",
    description:
      "Whole almonds slow-tumbled in Sidr honey until each carries a thin amber glass of sweetness. A study in restraint.",
    price: 68,
    currency: "SAR",
    images: img("honey-glazed-almonds"),
    weight: "300g",
    sku: "LEOR-NT-202",
    barcode: "6281000002029",
    stock: 41,
    lowStockThreshold: 12,
    rating: 4.9,
    reviewCount: 93,
    tags: ["almonds", "honey", "sweet"],
    attributes: { Glaze: "Sidr honey", Origin: "California / Yemen" },
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    onSale: false,
    createdAt: "2025-10-22T09:00:00Z",
  },
  {
    id: "p-203",
    slug: "smoked-pistachios",
    name: "Oak-Smoked Pistachios",
    nameAr: "فستق مدخن",
    category: "nuts",
    shortDescription: "Iranian pistachios cold-smoked over oak for six hours.",
    description:
      "Premium Iranian pistachios, shells split by hand, cold-smoked over oak. Deep, savoury, impossible to stop eating.",
    price: 92,
    salePrice: 79,
    currency: "SAR",
    images: img("smoked-pistachios"),
    weight: "300g",
    sku: "LEOR-NT-203",
    barcode: "6281000002036",
    stock: 18,
    lowStockThreshold: 10,
    rating: 4.7,
    reviewCount: 55,
    tags: ["pistachio", "smoked", "savoury"],
    attributes: { Smoke: "Oak, 6 hours", Origin: "Iran" },
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    onSale: true,
    createdAt: "2026-02-14T09:00:00Z",
  },
  {
    id: "p-204",
    slug: "candied-pecans-cinnamon",
    name: "Cinnamon Candied Pecans",
    nameAr: "جوز البقان بالقرفة",
    category: "nuts",
    shortDescription: "Georgia pecans in a delicate cinnamon-vanilla shell.",
    description:
      "Halved pecans candied in copper kettles with Ceylon cinnamon and Madagascar vanilla. The scent alone is worth the price.",
    price: 74,
    currency: "SAR",
    images: img("candied-pecans-cinnamon"),
    weight: "300g",
    sku: "LEOR-NT-204",
    barcode: "6281000002043",
    stock: 33,
    lowStockThreshold: 10,
    rating: 4.8,
    reviewCount: 61,
    tags: ["pecan", "candied", "cinnamon"],
    attributes: { Spice: "Ceylon cinnamon", Vanilla: "Madagascar" },
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    onSale: false,
    createdAt: "2026-05-28T09:00:00Z",
  },

  // ——— Accessories ———
  {
    id: "p-301",
    slug: "leor-brass-pour-over",
    name: "LEOR Brass Pour-Over Set",
    nameAr: "طقم التقطير النحاسي",
    category: "accessories",
    shortDescription: "Hand-spun brass dripper with walnut collar and glass carafe.",
    description:
      "Designed in-house and spun by hand: a brass V-form dripper with a turned walnut collar, paired with a 600ml borosilicate carafe. Ages beautifully.",
    price: 340,
    currency: "SAR",
    images: img("leor-brass-pour-over"),
    weight: "1.2kg",
    sku: "LEOR-AC-301",
    barcode: "6281000003019",
    stock: 12,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 38,
    tags: ["pour-over", "brass", "brewing"],
    attributes: { Material: "Brass, walnut, borosilicate", Capacity: "600ml" },
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
    onSale: false,
    createdAt: "2025-12-18T09:00:00Z",
  },
  {
    id: "p-302",
    slug: "precision-hand-grinder",
    name: "Precision Hand Grinder",
    nameAr: "مطحنة يدوية دقيقة",
    category: "accessories",
    shortDescription: "48mm steel burrs, 60 click-stop settings, aluminium body.",
    description:
      "Machined from a single billet of aluminium with 48mm coated steel burrs and 60 externally adjustable settings — from Turkish-fine to cold-brew-coarse.",
    price: 295,
    salePrice: 255,
    currency: "SAR",
    images: img("precision-hand-grinder"),
    weight: "780g",
    sku: "LEOR-AC-302",
    barcode: "6281000003026",
    stock: 21,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 74,
    tags: ["grinder", "burr", "travel"],
    attributes: { Burrs: "48mm coated steel", Settings: "60 click-stops", Capacity: "35g" },
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    onSale: true,
    createdAt: "2026-01-25T09:00:00Z",
  },
  {
    id: "p-303",
    slug: "ceramic-cupping-set",
    name: "Ceramic Cupping Set",
    nameAr: "طقم التذوق الخزفي",
    category: "accessories",
    shortDescription: "Six navy-glazed cupping bowls with gold-lined rims.",
    description:
      "Stoneware cupping bowls in LEOR navy with a hand-applied gold rim. 220ml, stackable, dishwasher-safe despite appearances.",
    price: 180,
    currency: "SAR",
    images: img("ceramic-cupping-set"),
    weight: "2.1kg",
    sku: "LEOR-AC-303",
    barcode: "6281000003033",
    stock: 16,
    lowStockThreshold: 6,
    rating: 4.7,
    reviewCount: 29,
    tags: ["ceramic", "cupping", "tableware"],
    attributes: { Pieces: "6", Capacity: "220ml", Glaze: "Navy with gold rim" },
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    onSale: false,
    createdAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "p-304",
    slug: "gooseneck-kettle",
    name: "Temperature Gooseneck Kettle",
    nameAr: "غلاية التقطير الحرارية",
    category: "accessories",
    shortDescription: "0.9L matte-black kettle with ±1°C hold and counterweighted handle.",
    description:
      "Variable temperature with one-degree precision and a 60-minute hold. The counterweighted handle makes a slow spiral pour effortless.",
    price: 385,
    currency: "SAR",
    images: img("gooseneck-kettle"),
    weight: "1.4kg",
    sku: "LEOR-AC-304",
    barcode: "6281000003040",
    stock: 9,
    lowStockThreshold: 5,
    rating: 4.9,
    reviewCount: 51,
    tags: ["kettle", "electric", "pour-over"],
    attributes: { Capacity: "0.9L", Precision: "±1°C", Hold: "60 min" },
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    onSale: false,
    createdAt: "2026-06-05T09:00:00Z",
  },

  // ——— Gift Boxes ———
  {
    id: "p-401",
    slug: "leor-grand-hamper",
    name: "The LEOR Grand Hamper",
    nameAr: "سلة ليور الكبرى",
    category: "gift-boxes",
    shortDescription: "Our definitive gift: coffee, chocolate, nuts and brass accessories.",
    description:
      "Signature espresso, Madagascar 70%, the pistachio praliné collection, royal mixed nuts and a brass scoop — presented in a keepsake navy box with gold foiling and a hand-written card.",
    price: 495,
    currency: "SAR",
    images: img("leor-grand-hamper"),
    weight: "2.8kg",
    sku: "LEOR-GB-401",
    barcode: "6281000004016",
    stock: 15,
    lowStockThreshold: 5,
    rating: 5.0,
    reviewCount: 87,
    tags: ["gift", "hamper", "corporate"],
    attributes: { Contents: "5 items", Presentation: "Keepsake box, gold foil", Card: "Hand-written" },
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    onSale: false,
    createdAt: "2025-11-10T09:00:00Z",
  },
  {
    id: "p-402",
    slug: "petit-tasting-box",
    name: "Petit Tasting Box",
    nameAr: "صندوق التذوق الصغير",
    category: "gift-boxes",
    shortDescription: "Three chocolates and two coffees in a slim discovery set.",
    description:
      "A slender introduction to LEOR: three single-origin bars and two 100g coffees, with tasting notes written by our head roaster.",
    price: 185,
    salePrice: 165,
    currency: "SAR",
    images: img("petit-tasting-box"),
    weight: "650g",
    sku: "LEOR-GB-402",
    barcode: "6281000004023",
    stock: 27,
    lowStockThreshold: 8,
    rating: 4.8,
    reviewCount: 44,
    tags: ["gift", "tasting", "discovery"],
    attributes: { Contents: "3 bars + 2 coffees", Notes: "By our head roaster" },
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    onSale: true,
    createdAt: "2026-02-20T09:00:00Z",
  },

  // ——— Seasonal ———
  {
    id: "p-501",
    slug: "ramadan-nights-collection",
    name: "Ramadan Nights Collection",
    nameAr: "تشكيلة ليالي رمضان",
    category: "seasonal",
    shortDescription: "Date-filled chocolates and Arabic-spiced coffee for the holy month.",
    description:
      "A limited collection for Ramadan: qamar al-din pralinés, date and cardamom truffles, and our Arabic coffee blend with saffron. Available for a moon's cycle only.",
    price: 220,
    currency: "SAR",
    images: img("ramadan-nights-collection"),
    weight: "900g",
    sku: "LEOR-SN-501",
    barcode: "6281000005013",
    stock: 22,
    lowStockThreshold: 8,
    rating: 4.9,
    reviewCount: 76,
    tags: ["ramadan", "limited", "gift"],
    attributes: { Availability: "Seasonal", Contents: "Truffles, pralinés, Arabic coffee" },
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    onSale: false,
    createdAt: "2026-06-10T09:00:00Z",
  },
  {
    id: "p-502",
    slug: "winter-spice-hot-chocolate",
    name: "Winter Spice Drinking Chocolate",
    nameAr: "شوكولاتة الشتاء الساخنة",
    category: "seasonal",
    shortDescription: "65% flakes with cinnamon, orange peel and a breath of clove.",
    description:
      "Our drinking chocolate, wintered: Ceylon cinnamon, candied orange peel and clove folded through 65% couverture flakes. December in a cup.",
    price: 64,
    currency: "SAR",
    images: img("winter-spice-hot-chocolate"),
    weight: "250g",
    sku: "LEOR-SN-502",
    barcode: "6281000005020",
    stock: 5,
    lowStockThreshold: 10,
    rating: 4.7,
    reviewCount: 33,
    tags: ["winter", "drinking-chocolate", "limited"],
    attributes: { Cacao: "65%", Spices: "Cinnamon, orange, clove" },
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    onSale: false,
    createdAt: "2025-12-01T09:00:00Z",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r-1",
    productId: "p-001",
    author: "Sarah M.",
    rating: 5,
    title: "The best coffee I've ever brewed at home",
    body: "The jasmine aroma when you open the bag is unreal. Brewed as pour-over it's delicate and sweet — exactly as described.",
    date: "2026-05-14T10:00:00Z",
    verified: true,
  },
  {
    id: "r-2",
    productId: "p-001",
    author: "Khalid A.",
    rating: 5,
    title: "Worth every riyal",
    body: "Freshly roasted, shipped fast, beautifully packaged. LEOR has become my monthly ritual.",
    date: "2026-04-02T10:00:00Z",
    verified: true,
  },
  {
    id: "r-3",
    productId: "p-001",
    author: "Noura F.",
    rating: 4,
    title: "Lovely, slightly light for my taste",
    body: "Gorgeous florals but I prefer a touch more body. Their signature espresso is more my style.",
    date: "2026-03-19T10:00:00Z",
    verified: false,
  },
  {
    id: "r-4",
    productId: "p-102",
    author: "Abdullah R.",
    rating: 5,
    title: "Bought as a gift, kept half for myself",
    body: "The pistachio filling is outrageous. Presentation is on another level — navy box, gold ribbon.",
    date: "2026-05-30T10:00:00Z",
    verified: true,
  },
  {
    id: "r-5",
    productId: "p-401",
    author: "Corporate Client",
    rating: 5,
    title: "Ordered 40 for our partners",
    body: "LEOR handled a large corporate order flawlessly. Hand-written cards in Arabic and English. Impeccable.",
    date: "2026-06-11T10:00:00Z",
    verified: true,
  },
  {
    id: "r-6",
    productId: "p-301",
    author: "Faisal T.",
    rating: 5,
    title: "Heirloom quality",
    body: "The brass has already started developing a patina. Pours beautifully. This will outlive me.",
    date: "2026-05-08T10:00:00Z",
    verified: true,
  },
];

export const COUPONS: Coupon[] = [
  { code: "WELCOME10", type: "percent", value: 10 },
  { code: "LEOR50", type: "fixed", value: 50, minSubtotal: 400 },
  { code: "GOLD15", type: "percent", value: 15, minSubtotal: 250 },
];

// ——— Query helpers (single data access layer; swap to REST client via NEXT_PUBLIC_API_URL) ———

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function getProductsByCategory(slug: string): Product[] {
  return PRODUCTS.filter((p) => p.category === slug);
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter((p) => p.isFeatured);
}

export function getBestSellers(): Product[] {
  return PRODUCTS.filter((p) => p.isBestSeller);
}

export function getNewArrivals(): Product[] {
  return [...PRODUCTS]
    .sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt))
    .slice(0, 8);
}

export function getOnSaleProducts(): Product[] {
  return PRODUCTS.filter((p) => p.onSale);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter((p) => p.category === product.category && p.id !== product.id).slice(0, limit);
}

export function getReviewsForProduct(productId: string): Review[] {
  return REVIEWS.filter((r) => r.productId === productId);
}

export function searchProducts(query: string): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return PRODUCTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.nameAr.includes(q) ||
      p.shortDescription.toLowerCase().includes(q) ||
      p.sku.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q)) ||
      p.category.includes(q)
  );
}

export function validateCoupon(code: string, subtotal: number) {
  const coupon = COUPONS.find((c) => c.code.toLowerCase() === code.trim().toLowerCase());
  if (!coupon) return { ok: false as const, error: "This code isn't valid." };
  if (coupon.minSubtotal && subtotal < coupon.minSubtotal)
    return { ok: false as const, error: `Requires a minimum subtotal of ${coupon.minSubtotal} SAR.` };
  return { ok: true as const, coupon };
}
